# Generated by Django 4.2.2 on 2024-06-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_review_date_added_alter_review_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
