# Generated by Django 4.2.2 on 2024-06-24 17:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_item_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description_long',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
