# Generated by Django 4.2.2 on 2024-06-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_description_long'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
